### ISSUE TITLE
Add options Flags to CLI

### ISSUE THREAD

**Issue by una** [una/sass-director#11]
--sass for .sass syntax and --nounderscore to not use partials

**Comment by jonathantneal** [comment]
I’ve added both of these as well as a `--watch` statement. The major changes coming later today are:

- Add `—sass` option to create .sass partials
- Add `—no-underscore` option to create partials without an underscore
- Strip comments before parsing `@import` statements
- Log individual file and folder creation instead of logging a summary
- Watch manifest file for changes
- Create partials when @import statement is added
- Remove partials when @import statements is removed and partial is empty

**Comment by una** [comment]
That sounds great!

With the --watch implemented, it would make sense to use this module in a task-running scenario

**Comment by una** [comment]
See PR 19
